== Integrationsprozesse
Die Integrationsprozesse sind dafür verantwortlich, dass die für den Betrieb des ÖREB-Katasters notwendigen Daten in der ÖREB-Datenbank integriert werden. Konkret sind das:

- ÖREB-Daten 
- Codelisten (nur Bund)
- Bundesgesetze und -verordnungen, sowie kantonale Gesetze und Verordnungen
- ÖREB-Rahmenmodell Teilmodell «Konfiguration»
- AV-Daten (inkl. Grundbuchkreise und amtliches Ortschaftsverzeichnis)

[#inbetriebnahme]
=== Inbetriebnahme (Daten-Erstintegration)
Bei der Daten-Erstintegration in die Edit-DB für spätere Bearbeitung der kantonalen Konfigurationsdaten ist die Importreihenfolge der verschiedenen Datensätze entscheidend. Es handelt sich ausschliesslich um INTERLIS-Transferdateien. Diese sind teilweise voneinander abhängig, so dass in der Datenbank Fremdschlüssel entstehen. Dies trifft vor allem auf die Konfigurationen zu. Es ergibt sich folgende Reihenfolge, wobei ab (6.) die Reihenfolge egal ist:

1. Zuständige Stellen (Kanton)
2. Gesetze (Kanton)
3. Gesetze (Bund)
4. Themen (Bund)
5. Themen (Kanton)
6. Logos (Kanton)
7. Texte (Kanton)
8. Verfügbarkeit (Kanton)
9. Grundbuchkreise (Kanton)

Siehe auch https://github.com/sogis-oereb/oereb-gretljobs/blob/main/DEVELOP.md#import-config-data-into-gdi-db[DEVELOP.md] für die Dataset-Identifier und ili2pg-Befehle.

Daraus ergibt sich auch die Reihenfolge wie die Gretl-Jobs für die Konfigurationen ausgeführt werden müssen, um Daten von der Edit-DB in die ÖREB-DB zu transferieren:

1. `oerebv2_bundesgesetze`
2. `oerebv2_bundeskonfiguration`
3. `oerebv2_konfiguration_zustaendigestellen`
4. `oerebv2_konfiguration_gesetze`
5. `oerebv2_konfiguration_themen`
6. `oerebv2_konfiguration_logo`
7. `oerebv2_konfiguration_text`
8. `oerebv2_konfiguration_verfuegbarkeit`
9. `oerebv2_konfiguration_grundbuchkreis`

Die Reihenfolge der eigentlichen Daten (inkl. AV und PLZ/Ortschaft) spielt keine Rolle mehr.

[#datenintegration]
=== Datenintegration
Für die Datenintegration sämtlicher Daten in den ÖREB-Kataster werden GRETL-Jobs verwendet. Ein GRETL-Job kann je nach Datensatz unterschiedliche Aufgaben wahrnehmen:

Werden die ÖREB-Daten in der Edit-DB nachgeführt, werden diese zuerst in ein rahmenmodell-äquivalentes Schema in der Edit-DB umgebaut (z.B _arp_nutzungsplanung_oereb_v1_), anschliessend nach INTERLIS exportiert, validiert und in die ÖREB-Datenbank importiert. In der ÖREB-Datenbank sind zwei Schemen vorhanden: _stage_ und _live_. Zuerst werden die Daten in das _stage_-Schema importiert. Die Daten müssen von der zuständigen Stelle visuell validiert werden und freigegeben werden. Die WMS-Layer aus dem _stage_-Schema sind als geschützte Layer im Web GIS Client freigeschaltet, wo die Daten kontrolliert werden können.

Das Starten eines solchen Jobs wird in https://gretl.so.ch[_GRETL-Jenkins_] gemacht. Nur berechtigte Personen können den Job starten. Nach erfolgter visueller Validierung muss die berechtigte Person den Import in das _live_-Schema freigeben.

Sämtliche Aktionen in _GRETL-Jenkins_ werden transparent geloggt und sind nachvollziehbar. Die erzeugten Daten im Rahmenmodell werden archiviert und zusätzlich in S3 gespeichert.

=== Nachführung der ÖREB-Daten
==== Bundesdaten, Bundeskonfiguration, Bundesgesetze und -verordnungen
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_bundesdaten[`oerebv2_bundesdaten`]: ÖREB-Daten im Transfermodell. Werden jede Nacht importiert. +
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_bundesgesetze[`oerebv2_bundesgesetze`]: Gesetzlichen Grundlagen (Gesetz und Verordnungen) des Bundes. Werden manuell, «on demand» importiert. +
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_bundeskonfiguration[`oerebv2_bundeskonfiguration`]: Themen, Logos und Texte des Bundes. Werden manuell, «on demand» importiert.

Bundesdaten werden durch das zuständige Bundesamt nachgeführt und auf der Webseite https://data.geo.admin.ch/[https://data.geo.admin.ch/] im entsprechenden Unterordner bereitgestellt. Aus nicht nachvollziehbaren Gründen sind die ÖREB-Unterordner jedoch nicht direkt aufgelistet, sondern die Unterordner-Url muss mühsam selber zusammengestöpselt werden (aus Basis-Url und Themennamen). 

Die Bundeskonfiguration und die Bundesgesetze und -verordnungen sind auf der INTERLIS-Modell- und Datenablage zu finden (http://models.geo.admin.ch/V_D/OeREB/[http://models.geo.admin.ch/V_D/OeREB/]).

==== Kantonale Daten 
===== Nutzungsplanung
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_nutzungsplanung[`oerebv2_nutzungsplanung`]: Kommunale Nutzungsplanung. Job wird manuell, «on demand» ausgelöst.
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_nutzungsplanung_kanton[`oerebv2_nutzungsplanung_kanton`]: Kantonale Nutzungsplanung. Job wird manuell, «on demand» ausgelöst.

Die Daten der Nutzungsplanung (inkl. Waldabstandslinien und Lärmempfindlichkeitsstufen in Nutzungszonen) werden durch das AGI in den Datensatz in der Edit-DB eingepflegt.

===== Gewässerraum
GRETL-Jobs: +
https://github.com/sogis-oereb/oereb-gretljobs/tree/main/oerebv2_gewaesserraum[`oerebv2_gewaesserraum`]: Gewässerraum. Job wird manuell, «on demand» ausgelöst.

Die Daten des Gewässerraums liegen nicht in jeder Gemeinde mit Nutzungsplanung rechtsgültig vor. Aus diesem Grund muss das Thema bei der jeweiligen Gemeinde zuerst in der Edit-DB im Schema `agi_konfiguration_oerebv2` freigeschaltet werden. 

===== Waldgrenzen
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_waldgrenzen[`oerebv2_waldgrenzen`]: Job wird manuell, «on demand» ausgelöst.

Die Waldgrenzen werden in einem kantonalen Datenmodell durch das Amt für Geoinformation (AGI) in der Edit-DB nachgeführt.

===== Kataster der belasteten Standorte
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_belastete_standorte[`oerebv2_belastete_standorte`]: Job wird manuell, «on demand» ausgelöst.

Für die Nachführung des Katasters der belasteten Standorte setzt das Amt für Umwelt (AfU) die Software _altlast4web_ ein. Die Software läuft ausserhalb der GDI.

Die Daten des Kataster der belasteten Standorte werden durch _altlast4web_ als HTTP-Ressource (nur innerhalb des Kantonsnetzes verfügbar) bereitgestellt. Ein Datenumbau ist somit nicht notwendig. Der GRETL-Job muss die Daten nur validieren und in das _stage_- resp. _live_-Schema importieren. Eine visuelle Validierung durch die zuständige Stelle im _stage_-Schema findet jedoch ebenfalls statt.

===== Planerischer Gewässerschutz
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_grundwasserschutz[`oerebv2_grundwasserschutz`]: Job wird manuell, «on demand» ausgelöst.

Der planerische Gewässerschutz wird im MGDM durch das Amt für Geoinformation (AGI) in der Edit-DB nachgeführt.

===== Schützenswerte Objekte (Denkmal) / Geotope / Naturreservate
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_einzelschutz_denkmal[`oerebv2_einzelschutz_denkmal`]: Job wird manuell, «on demand» ausgelöst.  +
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_einzelschutz_geotop[`oerebv2_einzelschutz_geotop`]: Job wird manuell, «on demand» ausgelöst.
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_einzelschutz_naturreservat[`oerebv2_einzelschutz_naturreservat`]: Job wird manuell, «on demand» ausgelöst.

Denkmal: Diese ÖREB-Kataster-relevanten Daten werden durch das Amt für Archäologie und Denkmalschutz in der Fachanwendung _ArtPlus_ ausserhalb der kantonalen GDI nachgeführt. Eine Teilmenge der Daten wird täglich in die Edit-DB importiert.

Geotope werden in einem kantonalen Datenmodell durch das Amt für Umwelt (AFU) in der Edit-DB nachgeführt.

Naturreservate werden in einem kantonalen Modell durch das Amt für Geoinformation (AGI) in der Edit-DB nachgeführt.

=== Nachführung der kantonalen Konfiguration
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_zustaendigestellen[`oerebv2_konfiguration_zustaendigestellen`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_gesetze[`oerebv2_konfiguration_gesetze`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_themen[`oerebv2_konfiguration_themen`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_logo[`oerebv2_konfiguration_logo`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_text[`oerebv2_konfiguration_text`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_verfuegbarkeit[`oerebv2_konfiguration_verfuegbarkeit`] + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oerebv2_konfiguration_grundbuchkreis[`oerebv2_konfiguration_grundbuchkreis`]

Bis auf `oerebv2_konfiguration_verfuegbarkeit` sind sätmliche Konfigurations-Jobs «on demand»-Jobs. Die Verfügbarkeit muss täglich ausgeführt werden, damit das Datum des Standes der amtlichen Vermessung aktualisiert wird.

Die Daten werden durch das Amt für Geoinformation (AGI) nachgeführt. Siehe dazu auch eine ausführliche Anleitung: `H:\BJSVW\Agi\ÖREB-Kataster\Nachführung\Konfiguration_Annex\Anleitung ÖREB-Themen freischalten_Version2.0.docx`.

=== Nachführung Daten der amtlichen Vermessung (inkl. Grundbuchkreise und amtliches Ortschaftsverzeichnis)
GRETL-Jobs: + 
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oereb_av[`oereb_av`]: Job wird jede Nacht automatisch ausgeführt. +
https://github.com/sogis-oereb/oereb-gretljobs/tree/master/oereb_plzo[`oereb_plzo`]: Job wird jede Nacht automatisch ausgeführt. +

Die Daten werden mit einem GRETL-Job aus der Edit-DB direkt («Db2Db-Task») in die ÖREB-Datenbank kopiert. Die AV-Daten werden von den zuständigen Nachführungsgeometern mindestens einmal wöchentlich geliefert und anschliessend automatisch in die Edit-DB importiert.
